---
abstract: 'Generates test data for mysql easily.'
author:
  - 'Takashi Egawa <egawa.takashi@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.88, CPAN::Meta::Converter version 2.132140'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Data-HandyGen-mysql
no_index:
  directory:
    - t
    - inc
requires:
  Class::Accessor::Lite: 0
  DBD::mysql: 0
  DBI: 1.38
  Data::Dumper: 0
  DateTime: 0
  Getopt::Long: 0
  JSON: 0
  SQL::Maker: 0
  Test::Exception: 0
  Test::More: 0.87_01
  Test::Warn: 0
  Test::mysqld: 0
  YAML: 0
version: v0.0.1
